### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by nathanfranke** [adamratzman/Java-Discord-OAuth-Library#1]
I am getting this error with the default library.

```
OAuthSettings authSettings = new OAuthSettings(DiscordBot.jda.getSelfUser().getName(), DiscordBot.HOST, DiscordBot.HOST + "/token", "1.0");
BotSettings botSettings = new BotSettings(DiscordBot.jda.getSelfUser().getId(), "SECRET", DiscordBot.jda.getToken());
try {
	System.out.println(new OAuthManager(authSettings, botSettings).getToken(code));
} catch (OAuthException e) {
	e.printStackTrace();
}
```

**Comment by adamint** [comment]
Hey Nathan,Thanks for using the library! It hasn’t been updated for a while (I’ll be working on it in a few hours) so it’s possible the discord api has changed but I doubt it. Check in the instantiation that you’re using the bot id---- On Thu, 19 Apr 2018 23:00:57 -0700  nathanthensooper<notifications@github.com> wrote ----I am getting this error with the default library. OAuthSettings authSettings = new OAuthSettings(DiscordBot.jda.getSelfUser().getName(), DiscordBot.HOST, DiscordBot.HOST + "/token", "1.0"); BotSettings botSettings = new BotSettings(DiscordBot.jda.getSelfUser().getId(), "SECRET", DiscordBot.jda.getToken()); try { System.out.println(new OAuthManager(authSettings, botSettings).getToken(code)); } catch (OAuthException e) { e.printStackTrace(); }  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by adamint** [comment]
@nathanthesnooper Please update your jitpack reference. The library is now updated and this works. Comment back once you have tried.

**Comment by nathanfranke** [comment]
@adamint 
How do I update my jitpack reference? What I did was put your library in my code (Shading)
I am not using Maven or Gradle, just pure java in Eclipse

Anyways, here is my error.
```
BotName: BotName
Host: http://my.ip.add.ress:8000
RedirectURI: http://my.ip.add.ress:8000/token
ID: TonsOfRandomNumbers
Secret: TonsOfRandomCharacters
Token: TonsOfRandomCharacters
Code: TonsOfRandomCharacters
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=401, URL=https://discordapp.com/api/oauth2/token
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:682)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:629)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:261)
	at org.jsoup.helper.HttpConnection.post(HttpConnection.java:256)
	at com.adamratzman.oauth.utils.HttpRetrieval.retrieveToken(HttpRetrieval.java:24)
	at com.adamratzman.oauth.main.DiscordAuthenticator.getToken(DiscordAuthenticator.java:34)
	at net.nathanfranke.utils.Oauth2.getToken(Oauth2.java:107)
	at net.nathanfranke.DiscordBot$5.handle(DiscordBot.java:242)
	at net.nathanfranke.utils.HTTPHandler.handle(HTTPHandler.java:29)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:748)
```

Code:
```
String botName = DiscordBot.jda.getSelfUser().getName();
String host = DiscordBot.HOST;
String redirectUri = (DiscordBot.HOST + "/token");
String id = DiscordBot.jda.getSelfUser().getId();
String secret = ("SECRET");
String token = ("MYTOKEN");
System.out.println("BotName: " + botName + 
		"\nHost: " + host + 
		"\nRedirectURI: " + redirectUri + 
		"\nID: " + id + 
		"\nSecret: " + secret + 
		"\nToken: " + token + 
		"\nCode: " + code);
DiscordAuthenticator authenticator = new DiscordAuthenticator.Builder()
		.setOauthConfiguration(host, redirectUri)
		.setBotConfiguration(botName, id, secret, token)
		.build();
authenticator.getToken(code);
```

According to [Discord](https://discordapp.com/developers/docs/topics/response-codes), 401 means "The Authorization header was missing or invalid"

**Comment by nathanfranke** [comment]
I am trying to fix the code, I managed to fix all the Jsoup errors so now it's just response errors
```
System.out.println(Jsoup.connect(baseUrl + "/oauth2/token").ignoreContentType(true).ignoreHttpErrors(true)
		            .header("Content-Type", "application/x-www-form-urlencoded")
                    .header("Authorization", "Authorization: Bot " + authenticator.getBotToken())
                    .header("cache-control", "no-cache")
		            .data("client_id", authenticator.getBotId())
		            .data("client_secret", authenticator.getBotSecret())
		            .data("grant_type", "authorization_code")
		            .data("code", code)
		            .data("redirect_uri", "https://www.example.com").post().text());
```
Response:
{"error": "invalid_grant"}
Token is just the (IsjE8W3b) garbled text, without "Bot " at the front, incase you were wondering

**Comment by adamint** [comment]
Let me look. Are you trying to use the built-in methods or your own?

**Comment by nathanfranke** [comment]
I am editing the methods you made.

**Comment by nathanfranke** [comment]
Fixed it! (Not me, someone on API Help)
Apparently, the URI needs to match the whitelisted one on your apps, so example.com won't work.
Also, remove the Authentication Bot thing, it is not needed

**Comment by adamint** [comment]
Great, glad it's working! The bot authentication is needed, it is one of the available authentication methods. By the way, why were you trying to edit the api methods?
